# Generated by Django 4.0.1 on 2022-01-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('categories', models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports')], max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
